In [1]:
import numpy as np

arr = np.array([[10,20,30,40],[50,60,70,80],[20,40,60,80]])
print (arr[2,2])
print(np.shape(arr))
print(np.size(arr))

60
(3, 4)
12


In [7]:
arr1 = np.array([30,40,60,80,20])
arr2 = np.array([10,30,50,20,60])
print(arr1+arr2)
print(np.add(arr1,arr2))


[ 40  70 110 100  80]
[ 40  70 110 100  80]


In [9]:
arr1 = np.array([[30,40],[80,20]])
arr2 = np.array([[10,30],[20,60]])
print(arr1+arr2)
print(np.add(arr1,arr2))


[[ 40  70]
 [100  80]]
[[ 40  70]
 [100  80]]


In [12]:
arr1 = np.array([[30,40],[80,20]])
arr2 = np.array([[10,30],[20,60]])
print(arr1-arr2)
print(np.subtract(arr1,arr2))


[[ 20  10]
 [ 60 -40]]
[[ 20  10]
 [ 60 -40]]


In [13]:
arr1 = np.array([[30,40],[80,20]])
arr2 = np.array([[10,30],[20,60]])
print(arr1*arr2)
print(np.multiply(arr1,arr2))


[[ 300 1200]
 [1600 1200]]
[[ 300 1200]
 [1600 1200]]


In [14]:
arr1 = np.array([[30,40],[80,20]])
arr2 = np.array([[10,30],[20,60]])
print(arr1/arr2)
print(np.divide(arr1,arr2))


[[3.         1.33333333]
 [4.         0.33333333]]
[[3.         1.33333333]
 [4.         0.33333333]]


In [15]:
arr1 = np.array([30,40,80,20])
arr2 = np.array([2])
print(np.power(arr1,arr2))


[ 900 1600 6400  400]


In [17]:
arr1 = np.array([900, 1600, 6400, 400])
print(np.sqrt(arr1))

[30. 40. 80. 20.]


In [4]:
arr1 = ([30,20,10])
arr2 = ([10,20,30])
print(arr1+arr2)
print(np.concatenate([arr1,arr2]))

[30, 20, 10, 10, 20, 30]
[30 20 10 10 20 30]


In [5]:
print(np.hstack([arr1,arr2]))  # horizontal concatenation
print(np.vstack([arr1,arr2]))  # vertical concatenation

[30 20 10 10 20 30]
[[30 20 10]
 [10 20 30]]


In [6]:
arr1 = ([[1,2,3],[4,5,6]])
arr2 = ([[1,2,3],[4,5,6]])

print(np.hstack([arr1,arr2]))
print(np.vstack([arr1,arr2]))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [10]:
a = np.array([12,23,34,45])
print(np.append(a,[56,67]))
print(np.insert(a,3,78))  #array,index,value
print(np.delete(a,2))

[12 23 34 45 56 67]
[12 23 34 78 45]
[12 23 45]


In [11]:
arr = (54,3,97,12,999,65,154)
print(np.sort(arr))

[  3  12  54  65  97 154 999]


In [20]:
import statistics as sts
arr1 = ([100,200,300,400,500,600,200])

print(np.mean(arr1))
print(np.median(arr1))
print(sts.mode(arr1))
print(np.std(arr1))
print(np.var(arr1))

328.57142857142856
300.0
200
166.5986255670086
27755.10204081633


In [24]:
# -1 represents inversely proportional relationship
# 1 represents a proportional relationship
# 0 represents no relationship
prices = ([100,200,300,400,500])
sales = ([12,14,15,16,18])

print(np.corrcoef([prices,sales]))

[[1.         0.98994949]
 [0.98994949 1.        ]]
